url: https://meralsa.github.io
baseurl: ""

# Site settings
title: Meral Sahin
email: meralsa@icloud.com
description: "Meral's Bewerbungsprofil"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/m-sa/

# Postal address (add as many lines as necessary)
address:
  - line: Wachtelstr. 53B
  - line: 22305 Hamburg, Germany

# Build settings
markdown: kramdown
permalink: pretty
